export AuthPage from './AuthPage/AuthPage.jsx';
export ContactPage from './ContactPage/ContactPage.jsx';
export DashboardPage from './DashboardPage/DashboardPage.jsx';
export EditorPage from './EditorPage/EditorPage.jsx';
export FaqPage from './FaqPage/FaqPage.jsx';
export HomePage from './HomePage/HomePage.jsx';
export LandingPage from './LandingPage/LandingPage.jsx';
export NotFoundPage from './NotFoundPage/NotFoundPage.jsx';
export SearchPage from './SearchPage/SearchPage.jsx';
